### ISSUE TITLE
Expose OTP resent period

### ISSUE THREAD

**Issue by banterCZ** [wultra/enrollment-server#827]
OTP resent period is configurable and may be changed. Mobile application needs to configure it as well. But these two values may be out of sync. Expose the value at REST API, where the mobile application may take it.

See `enrollment-server-onboarding.onboarding-process.otp.resend-period:30s`

**Comment by kober32** [comment]
Few insights:

Endpoint `/api/identity/status` already returns similar (or maybe the same, but it's different flow for the app) information here: https://github.com/wultra/enrollment-server/blob/609a81319e783d489c4ebdf3e0f9284ce1bffaaa/enrollment-server-onboarding-api-model/src/main/java/com/wultra/app/enrollmentserver/api/model/onboarding/response/data/ConfigurationDataDto.java#L27

It would be nice if this could be just seconds (Long) instead of ISO 8601 format, which does not have native support on mobile. To ensure back compatibility, it would need to be a new property.

Also, during the activation process, we need this information in 2 endpoints: 
- `/api/onboarding/start`
- `/api/onboarding/status`
The reason is that the app does not call the status endpoint every time.
