### ISSUE TITLE
Improve error handling in MobileTokenController

### ISSUE THREAD

**Issue by banterCZ** [wultra/enrollment-server#913]
`MobileTokenController` error handling is too strict. E.g. `/operation/history` catches `PowerAuthClientException` and remaps it to `MobileTokenAuthException`. The result is `401 Unauthorized` without any detail. Actually, the detail is only in the enrollment-server log.
We should provide some hints. The mobile application must be able to handle it.

❗ For missing authorization, 401 **must** remain.

Consider other methods in this controller as well.

**Comment by jnpsk** [comment]
Could be tested by validating the correct error codes are propagated:

This controller handles endpoints on the path `/api/auth/token/app`

**INVALID_APPLICATION** (status 400) happens if the application specified by `applicationId` in a request does not exist. Relevant to:
```
/operation/list
/operation/history
/operation/authorize
/operation/cancel
```

**INVALID_OPERATION** (status 400) may happen in any of the three cases:  
1. Operation specified by `operationId` in a request does not exist. Relevant to:
```
/operation/detail
/operation/detail/claim
/operation/authorize
/operation/cancel
```
2. Operation is not claimed to the user specified by `userId` in a request. Relevant to:
```
/operation/authorize
/operation/cancel 
```
3. Operation specified by `operationId` in a request is not in the `PENDING` state. Relevant to:
```
/operation/authorize
/operation/cancel 
```

**INVALID_REQUEST** (status 400) may happen in any of the six endpoints in case a required field of a request is missing.

**REMOTE_COMMUNICATION_ERROR** (status 409) may happen in any of the six endpoints in case an unexpected error caused by remote server occurs.
